// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/wizard-xie/realworld/internal/biz"
	"github.com/wizard-xie/realworld/internal/conf"
	"github.com/wizard-xie/realworld/internal/data"
	"github.com/wizard-xie/realworld/internal/server"
	"github.com/wizard-xie/realworld/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGorm(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	realwroldRepo := data.NewUserRepo(dataData, logger)
	realworldUsecase := biz.NewUserUsecase(realwroldRepo, logger)
	realworldService := service.NewRealworldService(realworldUsecase)
	httpServer := server.NewHTTPServer(confServer, realworldService, logger)
	grpcServer := server.NewGRPCServer(confServer, realworldService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
