name: golangci-lint
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: set go version
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: "--config=./.github/.golangci.yaml"
          only-new-issues: true